openapi: 3.0.0
info:
  description: User Registration
  version: 1.0.0
  title: UserRegistrationDemo
paths:
  /api/v1/user:
    post:
      summary: adds a user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
      responses:
        '201':
          description: user created
    get:
      summary: get a user
      responses:
        '200':
          description: user fetched
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
  /api/v1/user/{email}:
    post:
      summary: provide a password reset token
      parameters:
        - name: email
          in: path
          description: Email address of the user account to provide the reset token
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        '201':
          description: user created
components:
  schemas:
    Customer:
      type: object
      required:
        - email_address
        - password
      properties:
        email_address:
          type: string
          example: test@example.com
        password:
          type: string
          format: password
          example: someStrongPassword#
