# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: myservice
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'

provider:
  name: aws
  stage: dev
  runtime: nodejs12.x
  region: eu-central-1

plugins:
  - serverless-plugin-test-helper
  - serverless-openapi-integration-helper
  - serverless-random-gateway-deployment-id

custom:
  output:
    handler: scripts/output.handler
    file: stack.json

openApiIntegration:
  inputFile: api.yml
  package: true
  cors: true
  mapping:
    - stage: dev
      path: integrations
    - stage: test
      path: mocks

functions:

resources:
  Outputs:
    GatewayUrl: # This is the key that will be used in the generated outputs file
      Description: This is a helper for functional tests
      Value: !Join
        - ''
        - - 'https://'
          - !Ref ApiGatewayRestApi
          - '.execute-api.'
          - ${opt:region, self:provider.region}
          - '.amazonaws.com/'
          - ${opt:stage, self:provider.stage}

  Resources:
      ApiGatewayRestApi:
        Type: AWS::ApiGateway::RestApi
        Properties:
          ApiKeySourceType: HEADER
          Body: ~ #autogenerated by plugin
          Description: User Registration (${opt:stage, self:provider.stage})
          FailOnWarnings: false
          Name: ${opt:stage, self:provider.stage}-gateway
          EndpointConfiguration:
            Types:
              - REGIONAL
      ApiGatewayDeployment:
        Type: AWS::ApiGateway::Deployment
        Properties:
          Description: ${opt:stage, self:provider.stage}
          RestApiId: !Ref ApiGatewayRestApi
      ApiGatewayStage:
        Type: AWS::ApiGateway::Stage
        Properties:
          StageName: ${opt:stage, self:provider.stage}
          Description: ${opt:stage, self:provider.stage} Stage
          RestApiId: !Ref ApiGatewayRestApi
          DeploymentId: !Ref ApiGatewayDeployment
          Variables:
            BaseUrl: http://www.example.com

